#!/bin/bash
set -xeou pipefail

DOCKER_REGISTRY=${DOCKER_REGISTRY:-kubedb}

IMG=mysql
SUFFIX=v2

DB_VERSION="5.7.25"
TAG="5.7-$SUFFIX"

docker pull $DOCKER_REGISTRY/$IMG:$DB_VERSION

docker tag $DOCKER_REGISTRY/$IMG:$DB_VERSION "$DOCKER_REGISTRY/$IMG:$TAG"
docker push "$DOCKER_REGISTRY/$IMG:$TAG"
