#!/bin/bash
set -xeou pipefail

DOCKER_REGISTRY=${DOCKER_REGISTRY:-kubedb}

IMG=mysql
SUFFIX=v2

DB_VERSION=8.0
PATCH=8.0.14
TAG="$DB_VERSION-$SUFFIX"

docker pull $DOCKER_REGISTRY/$IMG:$PATCH

docker tag $DOCKER_REGISTRY/$IMG:$PATCH "$DOCKER_REGISTRY/$IMG:$TAG"
docker push "$DOCKER_REGISTRY/$IMG:$TAG"
